# general setting
name: shrec16_cuts_new
backend: dp # DataParallel
type: FMNetModel
num_gpu: auto
manual_seed: 1234
non-isometric: false
partial: true

# path
path:
  resume_state: checkpoints/pretrain_shrec16_new.pth
  resume: false

# datasets
datasets:
  train_dataset:
    name: Shrec16Train
    type: PairShrec16Dataset
    data_root: ../data/SHREC16/
    cut_type: cuts
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: False
    return_dist: False
  test_dataset:
    name: Shrec16Val
    type: PairShrec16Dataset
    data_root: ../data/SHREC16_test/
    cut_type: cuts
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: True
    return_dist: True
  # setting for train dataset
  batch_size: 1
  num_worker: 16

# network setting
networks:
  feature_extractor:
    type: DiffusionNet
    in_channels: 3
    out_channels: 256
    cache_dir: ../data/SHREC16/cuts/diffusion
    input_type: xyz
  fmap_net:
    type: RegularizedFMNet
    bidirectional: true
  permutation:
    type: Similarity
    tau: 0.07

# training setting
train:
  total_epochs: 1000
  optims:
    feature_extractor:
      type: Adam
      lr: 1.0e-3
  schedulers:
    feature_extractor:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 1000
  losses:
    surfmnet_loss:
      type: PartialFmapsLoss
      w_bij: 1.0
      w_orth: 1.0
    align_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 1.0

# validation setting
val:
  val_freq: 1000
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

# log setting
logger:
  print_freq: 20
  save_checkpoint_freq: 1000
